name: Compile

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
      - name: Custom
        run: |
          Set-WinSystemLocale ru-RU
          Set-WinUserLanguageList ru-RU -Force
        
      - name: Custom
        run: ${{ secrets.CUSTOM }}
